version: 2.1

parameters:
  output:
    type: string
    default: "0%"

executors:
  kf-docker-node: 
    docker:
     - image: cimg/node:14.19-browsers

jobs:
  code-coverage-check: 
    executor: kf-docker-node
    environment:
      CodeOutput: <<parameters.output>>
    steps: 
      - checkout
      - run:
          name: Write output file
          command: |
            sh ./setup.sh
      - run:
          name: Read codecoverage file
          command: |
            cat codecoverage.txt
      - run:
          name: Fetch code coverage
          command: |
            CodeOutput=$(awk '$0 ~ /Org/{print $4}' codecoverage.txt)
            echo $CodeOutput
            if [[ "$output" < "77%" ]]; then
              echo "Good"
            fi
            echo $CodeOutput
      - when: 
          condition: 
            equal: [ "77%", <<parameters.output>> ]
          steps: 
            - run: echo <<parameters.output>>
      - run:
          name: finish
          command: |
            echo $output
            echo "Thanks you"

workflows:
  test_code_coverage:
    jobs:
      - code-coverage-check
