version: 2.1

executors:
  kf-docker-node: 
    docker:
     - image: cimg/node:14.19-browsers

jobs:
  code-coverage-check: 
    executor: kf-docker-node
    steps: 
      - checkout
      - run:
          name: Write output file
          command: |
            sh ./setup.sh
      - run:
          name: Read codecoverage file
          command: |
            cat codecoverage.txt
      - run:
          name: Fetch code coverage
          command: |
            output=$(awk '$0 ~ /Org/{print $4}' codecoverage.txt)
            echo $output
            if [[ "$output" < "78%" ]]; then
                echo "Good"
            fi
      - run:
          name: finish
          command: |
            echo "Thanks you"

workflows:
  test_code_coverage:
    jobs:
      - code-coverage-check
