version: 2.1

orbs:
  browser-tools: circleci/browser-tools@x.y

executors:
  kf-docker-node: 
    docker:
     - image: cimg/node:14.19-browsers
     
commands:
  demo-when:
    steps:
      - run: echo "Welcome"
  end-task: 
    steps:
      - run:
          name: Cleanup
          command: echo "Good bye"

jobs:
  code-coverage-check: 
    docker:
      - image: cimg/openjdk:8.0-browsers
    steps: 
      - browser-tools/install-browser-tools
      - checkout
      - run:
          name: Write output file
          command: |
            sh ./setup.sh
      - run:
          name: Read codecoverage file
          command: |
            cat codecoverage.txt
      - run:
          name: Fetch code coverage
          command: |
            output=$(awk '$0 ~ /Org/{print $4}' codecoverage.txt)
            echo $output
            if [ ${output} != "78%" ]; then
              echo "Code coverage is affected"
            else
              echo "Code coverage is not affected"
            fi
      - run:
          name: finish
          command: |
            echo $output
            echo "Thanks you"

workflows:
  test_code_coverage:
    jobs:
      - code-coverage-check
